const jewelleryConfig = {
  necklace: [
    {
      position: [0.075, -1.3, 0],
      scale: [1.5, 1.25, 2],
      image: "./models/necklace/filter/necklace_14.png",
      label: "Ethereal Bloom",
      description: "Sterling silver, 4.5g, 17-inch chain",
      orgImage: "./models/necklace/original/necklace_14.jpg",
    },
    {
      position: [0.075, -1.3, 0],
      scale: [1.65, 1.25, 2],
      image: "./models/necklace/filter/necklace_15.png",
      label: "Celestial Charm",
      description: "Rose gold, 6g, 18-inch cable chain.",
      orgImage: "./models/necklace/original/necklace_15.jpg",
    },
    {
      position: [0.075, -1.5, 0],
      scale: [1.5, 1.75, 2],
      image: "./models/necklace/filter/necklace_16.png",
      label: "Serenity Chain",
      description: "Stainless steel, 5.2g, water-resistant, 16''",
      orgImage: "./models/necklace/original/necklace_16.jpg",
    },
    {
      position: [0.075, -1.4, 0],
      scale: [1.75, 1.25, 2],
      image: "./models/necklace/filter/necklace_17.png",
      label: "Golden Ember",
      description: "14K gold, 3.8g, 15-inch choker",
      orgImage: "./models/necklace/original/necklace_17.jpg",
    },
    {
      position: [0.075, -1.33, 0],
      scale: [1.85, 1.35, 2],
      image: "./models/necklace/filter/necklace_18.png",
      label: "Starlit Whisper",
      description: "White gold, 5g, 18-inch box chain",
      orgImage: "./models/necklace/original/necklace_18.jpg",
    },
    {
      position: [0.065, -1.25, 0],
      scale: [1.75, 1, 2],
      image: "./models/necklace/filter/necklace_20.png",
      label: "Mystic Orbit",
      description: "Platinum-plated, 5.5g, 18-inch link chain",
      orgImage: "./models/necklace/original/necklace_20.jpg",
    },
    {
      position: [0.065, -1.25, 0],
      scale: [1.6, 1, 2],
      image: "./models/necklace/filter/necklace_22.png",
      label: "Eclipse Shine",
      description: "Black titanium, 4g, 16-inch chain",
      orgImage: "./models/necklace/original/necklace_22.jpg",
    },
    {
      position: [0.075, -1.45, 0],
      scale: [1.4, 1.6, 2],
      image: "./models/necklace/filter/necklace_23.png",
      label: "Velvet Moon",
      description: "Opal charm, 3.6g, 17-inch snake chain",
      orgImage: "./models/necklace/original/necklace_23.jpg",
    },
    {
      position: [0.075, -1.3, 0],
      scale: [1.65, 1.1, 2],
      image: "./models/necklace/filter/necklace_24.png",
      label: "Velvet Moon",
      description: "Opal charm, 3.6g, 17-inch snake chain",
      orgImage: "./models/necklace/original/necklace_24.jpg",
    },
    {
      position: [0.075, -1.4, 0],
      scale: [1.35, 1.45, 2],
      image: "./models/necklace/filter/necklace_25.png",
      label: "Velvet Moon",
      description: "Opal charm, 3.6g, 17-inch snake chain",
      orgImage: "./models/necklace/original/necklace_25.jpg",
    },
  ],
  earrings: [
    {
      position: [-0.65, -0.05, 0],
      scale: [0.175, 0.2, 0.2],
      image: "./models/earrings/earrings_6.png",
      label: "Serenity Chain",
      description: "Stainless steel, 5.2g, water-resistant, 16''",
    },
    {
      position: [-0.65, -0.05, 0],
      scale: [0.12, 0.2, 0.2],
      image: "./models/earrings/earrings_12.png",
      label: "Eclipse Shine",
      description: "Black titanium, 4g, 16-inch chain",
    },
    {
      position: [-0.66, -0.05, 0],
      scale: [0.175, 0.2, 0.2],
      image: "./models/earrings/earrings_8.png",
      label: "Starlit Whisper",
      description: "White gold, 5g, 18-inch box chain",
    },
    {
      position: [-0.65, -0.045, 0],
      scale: [0.175, 0.2, 0.2],
      image: "./models/earrings/earrings_10.png",
      label: "Mystic Orbit",
      description: "Platinum-plated, 5.5g, 18-inch link chain",
    },
    {
      position: [-0.66, -0.125, 0],
      scale: [0.25, 0.45, 0.4],
      image: "./models/earrings/earrings_1.png",
      label: "Luna Glow",
      description: "18K gold-plated, 5g, adjustable 16-18''",
    },
    {
      position: [-0.66, -0.125, 0],
      scale: [0.15, 0.45, 0.4],
      image: "./models/earrings/earrings_2.png",
      label: "Luna Glow",
      description: "18K gold-plated, 5g, adjustable 16-18''",
    },
    {
      position: [-0.66, -0.125, 0],
      scale: [0.2, 0.45, 0.4],
      image: "./models/earrings/earrings_3.png",
      label: "Luna Glow",
      description: "18K gold-plated, 5g, adjustable 16-18''",
    },

    {
      position: [-0.66, -0.125, 0],
      scale: [0.2, 0.45, 0.4],
      image: "./models/earrings/earrings_7.png",
      label: "Golden Ember",
      description: "14K gold, 3.8g, 15-inch choker",
    },

    {
      position: [-0.66, -0.125, 0],
      scale: [0.25, 0.45, 0.4],
      image: "./models/earrings/earrings_9.png",
      label: "Aurora Gem",
      description: "Sapphire pendant, 4.2g, 17-inch chain",
    },

    {
      position: [-0.67, -0.125, 0],
      scale: [0.25, 0.45, 0.4],
      image: "./models/earrings/earrings_11.png",
      label: "Eclipse Shine",
      description: "Black titanium, 4g, 16-inch chain",
    },
  ],
};

const defaultBgImage = "./models/necklace/original/necklace_17.jpg";
